openapi: 3.0.1
info:
  title: monster-purple-worm
  x-cortex-tag: monster-purple-worm
  x-cortex-custom-metadata:
    alignment: chaotic-evil
    type: undead
    challenge_rating: 28
    legendary: false
    armor_class: 13
    hit_points: 168
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-purple-worm
      alias: github-token-test
